language: scala
scala:
- 2.11.11
script:
- sbt test package
notifications:
  slack:
    rooms:
      secure: InEqC8X08NoEWE5zpUp+NxDi7Tv6VJ4YSUxKT4Mv71LPDgOYDBR7kXSef+irUjU3z5RHL6npr/OGkdn2cgSHuaU0M/Vye19NOkOFgnzNKeRQWMnwASrEki5jEWrLMQu7KzIQa6BQEXwHkYORiMgEB+95eSDOXyfBfroLyUlrzGaGW2jXO8l5Tobzl5x2bP65NPHkdAlzPcREU3Li5p1WMl0AKPS2EAloCbDpUK5GtT272Uc/o2ZxEc6RHIiPF7WOwGy9Vdr/7kWNrsRQdYWSDZcw+O+AQi6Opklw4XcJXMtjkrEucF6PSAPoSv1kYAkbTNJf0/Gpp9QFjY48K5srdCHrtouomx33cMBY78ZMgGHwaix9q+O2pV9nKFOc45gRnQ8lPFQMRJiBZbzfhm31MJPx1WgKhsJo0JmNE9fLcaJgm15T2z3SzAivZ0KmOkLS67WjdgaJYnGsNgjeRn0GR+1HVeXNlHXkWV09cTxRTJVH7gSYjYHG9jbmBZMBqckce1ybylSnfEV4qjZAa91xH/DiHejNaxH7fVjysNWVfKS6RAPmhikswGzUJ4C/nnvpj3kUQnfb33eoWOlt1Gb8nRISKjo3l2fFMn0IzG/tWjCmOv9WFBhZmjlNuIgfmAwV1VRHuKePEO5dvhCL+jTp6baez+DCc2/ao2oMgckpQmM=
